# Generated by Django 2.0.7 on 2018-08-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20180728_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
    ]
