# Generated by Django 2.0.7 on 2018-07-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('armor', 'armor'), ('weapon', 'weapon')], default='armor', max_length=10),
        ),
    ]
