# Generated by Django 2.0.7 on 2018-08-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('armor', 'Armor'), ('weapon', 'Weapon')], default='armor', max_length=10),
        ),
    ]
